# .github/workflows/ci.yml

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          npm install

      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: https://api.render.com/deploy/srv-cndvvln79t8c738fevkg?key=7oL5lvmFV0s
        run: |
          curl "$deploy_url"
      
