# .github/workflows/ci.yml

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          npm install

      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: https://api.render.com/deploy/srv-cndtmo0l6cac73bh1dc0?key=04-fCDImG3U
        run: |
          curl "$deploy_url"
      
